### PR TITLE
Add pip check

### PR DESCRIPTION
**Pull request by jan-janssen**
The pip package requires `sympy==1.5.1` while the conda package is set to `sympy ==1.7` - I added a `pip check` to the tests section to demonstrate the issue.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
The issue was fixed in https://github.com/pycalphad/pycalphad/commit/55640ea2555270d11e80e9e60dcff3caf521b1b9 but this is not included in the pip package yet. So I guess the easiest way is to create a new pycalphad release to include the recent changes and then add the pip check afterwards to make sure the conda version and the pip version stay in sync.

**Comment by bocklund** [comment]
Thanks @jan-janssen. Since the version bump in pycalphad happened after tagging 0.8.4, I think it would make sense for to make a new conda-forge release of 0.8.4 to bump the build number and downgrade the sympy package to 1.5.1

**Comment by jan-janssen** [comment]
@bocklund It seems `sympy ==1.5.1` is not available for python 3.9

**Comment by jan-janssen** [comment]
@bocklund I added a patch for `sympy==1.7` so everything should be fine now.

**Comment by bocklund** [comment]
> @bocklund I added a patch for `sympy==1.7` so everything should be fine now. 

Thank you! This LGTM. The PR in the pycalphad repo was able to bump the pin without any changes, so I think the patch you wrote here should be safe.

@richardotis any comments?

**Review by bocklund — APPROVED** [review]

**Comment by richardotis** [comment]
Thanks for working on this. I agree with the solution here.

However, I am not happy that this mistake was even possible. There should be a way for us not to have to keep dependency information synchronized in so many different places.

**Comment by bocklund** [comment]
> Thanks for working on this. I agree with the solution here.
> 
> 
> 
> However, I am not happy that this mistake was even possible. There should be a way for us not to have to keep dependency information synchronized in so many different places.

I think it's my fault for introducing it 😳 - the `pip check` change that Jan introduced here should help for our PyPI dependencies. I wasn't aware of the feature. It might make sense to work that into our CI.

**Pull request merged**
