### PR TITLE
pycalphad 0.10.2

### PR DESCRIPTION
**Pull request by richardotis**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #49

### CODE REVIEW

**Comment by richardotis** [comment]
@conda-forge-admin, please rerender

**Comment by richardotis** [comment]
@jan-janssen @conda-forge/core Is there a way to trigger an automatic migration to python311 for a feedstock repo? I forgot to add Python 3.11 to the supported versions list in `setup.py`, but I notice other CF feedstocks seem to have received automated rebuild PRs without it.

**Comment by dopplershift** [comment]
It should happen by itself, once *ALL* (build, run, test) dependencies are available on Python 3.11. Have you verified that's the case, especially for any pinned versions?

**Comment by jan-janssen** [comment]
@richardotis to manually trigger the transition you can add the `python311.yaml` inside migrations: 
https://github.com/conda-forge/pycalphad-feedstock/blob/8b7784ad169db73fb9d121f5eee10c96e19c1f4f/.ci_support/migrations/python311.yaml

And afterwards do not forget to `rerender` the recipe.

**Comment by jan-janssen** [comment]
As an explanation on the https://conda-forge.org/status/#python311 page you can check the status of the python 3.11 migration. Pycalphad is listed here as `not-solvable`, which should be fixed once this pull request is merged. But I am not sure how long it takes for the bot to try the migration again.

**Comment by dopplershift** [comment]
I'd expect a few hours, maybe a day before the bot picks it up once this is merged.

**Comment by richardotis** [comment]
Thanks, all. I'm going to merge this and then wait a day before trying the manual migration approach.

**Pull request merged**
