### PR TITLE
Try to update to python 3.11

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@richardotis Is the restriction for `symengine` necessary? The comment says:
```
'symengine==0.9.0',  # python-symengine on conda-forge
```
and as `0.9.2` is available on `conda-forge` now. So I updated it from `0.9.0` to `0.9.2`. As only `0.9.2` is available for python 3.11, this update is required to be compatible with python 3.11.

**Comment by richardotis** [comment]
We should be able to bump to 0.9.2 in the pycalphad package now. The reason we pin symengine is because the release cycle across PyPI and conda-forge is unpredictable and there have been regressions in the past. Also, for conda-forge, it's important that the `symengine` binary package and the `python-symengine` bindings package stay in sync, which is easiest to do with a pin.

**Comment by richardotis** [comment]
@jan-janssen What we can do here is just cut a new release of pycalphad. (There are a few fixes that have been waiting for release anyway.) If you could submit a PR with this version bump and with `3.11` added to our GHA `test.yaml`, we'll let the automated infrastructure do most of the work, and that way we'll make sure py311 support is rolled out across both conda-forge and PyPI. Once that PR is merged I'll cut a new release, and conda-forge's automated version bump should do the rest.

**Comment by jan-janssen** [comment]
@richardotis I opened the corresponding pull request https://github.com/pycalphad/pycalphad/pull/456

**Comment by jan-janssen** [comment]
@richardotis As the pull request is merged, can you release a new version? then I adjust this pull request.

**Comment by richardotis** [comment]
Will do today.

**Pull request closed without merging**
